# DigitalOcean App Platform Configuration
# This file defines your complete application infrastructure

name: sales-order-manager
region: sfo

# Ingress configuration - handles routing
ingress:
  rules:
    - component:
        name: backend
      match:
        path:
          prefix: /api
    - component:
        name: backend
      match:
        path:
          prefix: /auth
    - component:
        name: backend
      match:
        path:
          prefix: /health
    - component:
        name: backend
      match:
        path:
          prefix: /readiness
    - component:
        name: backend
      match:
        path:
          prefix: /docs
    - component:
        name: backend
      match:
        path:
          prefix: /redoc
    - component:
        name: frontend
      match:
        path:
          prefix: /

# Backend API Service
services:
  - name: backend
    # Source configuration
    github:
      repo: FeliksML/sales-orders-manager
      branch: main
      deploy_on_push: true

    # Use Dockerfile for build
    dockerfile_path: backend/Dockerfile
    # source_dir removed - build context is repo root

    # Instance configuration
    instance_count: 2
    instance_size_slug: professional-xs  # 1GB RAM, 1 vCPU - $12/month per instance

    # HTTP configuration
    http_port: 8000

    # Health check
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3

    # Environment variables
    envs:
      # Database connection string from attached database
      - key: DATABASE_URL
        scope: RUN_TIME
        value: "${production-db.DATABASE_URL}"

      # Critical - Production secret key
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
        value: "SyRtO8XWcmHycEvVbz343bQJd96yy10JSneaeZftVH-gIgzoTzhO4iDw7BpeKhN9OVOaa5pLWTeCxxeKf0FFZA"

      - key: ENVIRONMENT
        scope: RUN_TIME
        value: "production"

      # Will be set after frontend deploys
      - key: FRONTEND_URL
        scope: RUN_TIME
        value: "${APP_URL}"

      # ReCAPTCHA secret key
      - key: RECAPTCHA_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
        value: "6LcqgxQsAAAAAPW1VDkdosH8WUc6krZWsZW8sVHs"

      # Email configuration
      - key: MAIL_USERNAME
        scope: RUN_TIME
        type: SECRET
        value: "salesmanagerverif@gmail.com"

      - key: MAIL_PASSWORD
        scope: RUN_TIME
        type: SECRET
        value: "oral omab uklw ufhn"

      - key: MAIL_FROM
        scope: RUN_TIME
        value: "noreply@salesorder.com"

      - key: MAIL_PORT
        scope: RUN_TIME
        value: "587"

      - key: MAIL_SERVER
        scope: RUN_TIME
        value: "smtp.gmail.com"

      - key: MAIL_STARTTLS
        scope: RUN_TIME
        value: "True"

      - key: MAIL_SSL_TLS
        scope: RUN_TIME
        value: "False"

# Frontend Static Site
static_sites:
  - name: frontend
    # Source configuration
    github:
      repo: FeliksML/sales-orders-manager
      branch: main
      deploy_on_push: true

    # Build configuration
    output_dir: frontend/dist
    build_command: cd shared && npm install && cd ../frontend && npm install && npm run build

    # Environment variables for build
    envs:
      - key: VITE_API_URL
        scope: BUILD_TIME
        value: "${backend.PUBLIC_URL}"

# Database
databases:
  - name: production-db
    cluster_name: db-postgresql-sfo3-98348

# Optional: Redis for caching/sessions (uncomment if needed)
# databases:
#   - name: redis
#     engine: REDIS
#     production: true

# Features
features:
  - buildpack-stack=ubuntu-22

# Alerts (optional - configure in UI)
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
